name: Github Pages Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: sterlingwes/gh-pages-deploy-action@v1.1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          source-directory: javadoc
          deploy-branch: javadoc
          build-command: yarn build
